### ISSUE TITLE
LoadError: UndefVarError: mac not defined

### ISSUE THREAD

**Issue by manojcent** [JuliaOpt/CPLEX.jl#135]
getting this error on window machine while running CPLEX

for t=1:PlanningPeriod
      for p=1:NumberofProducttypes
        for i=1:depot-nDepots
          @addConstraints(m,sum{z_ijtpv[j,i,t,p,v],v=1:NumerOfVehicle,j=1:i-1}+sum{z_ijtpv[j,i,t,p,v],v=1:NumerOfVehicle,j=i+1:depot-nDepots}
          -sum{z_ijtpv[i,j,t,p,v],v=1:NumerOfVehicle,j=1:i-1}-sum{z_ijtpv[i,j,t,p,v],v=1:NumerOfVehicle,jj=i+1:depot-nDepots}==r_itp[j,t,p]);
        end
      end
    end

**Comment by odow** [comment]
This should be `@constraint` (or `@addconstraint` depending on the version of JuMP you are using) instead of `@addconstraints`. It also looks like you are using an old version of JuMP. You may want to update and refer to the more recent syntax http://www.juliaopt.org/JuMP.jl/0.17/refexpr.html#methods.

**Comment by manojcent** [comment]
Thank you very much Oscar Dowson.
