### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by Reza-rn** [JuliaOpt/CPLEX.jl#185]
Hi 

I am using CPLEX 12.6. My problem is like that I am running a loop and at each iteration, I am solving a convex optimization problem by calling CPLEX in JuMP. However, after 80 iteration I face error 1001:out of memory. It seems memory usage is increased at each iteration of my solution and I need to kind of close or clean the model at each iteration. Can you help me how can I clean or close my model at each iteration?
Thanks.

**Comment by odow** [comment]
Hi @Reza-rn,

Thanks for using JuMP and CPLEX.jl. You should post questions like this over at the [Discourse forum](https://discourse.julialang.org/c/domain/opt). There are many more people who might be able to answer since not many people watch this repo.

Are you making a new JuMP model in every iteration? Or are you adding constraints to an existing model?

If it's the first, this should work
```julia
for i in 1:N
    model = Model(solver=CplexSolver())
    solve(model)
end
```
If it doesn't you could try putting the model in a function
```julia
function iteration(i::Int)
    model = Model(solver=CplexSolver())
    solve(model)
end
for i in 1:N
    iteration(i)
end
```

If it's the second, you just might not have enough memory. At least two copies of the model are stored: one in JuMP and one in CPLEX. In addition CPLEX may also stored a scaled version of the model so that is 3x the memory.

**Comment by Reza-rn** [comment]
Hi @odow 

Thanks for your response. Actually my problem is similar to the second model. However, I do not have function, instead, I am creating new JuMP object in each iteration with the same name as previous and call CPLEX to solve it with updated constraints and objective function. Despite I was creating a JuMP object with the same model name, but it seems the previous model still exists in the memory. Therefore, I need kind of **Model.clean** or **Model.end** to clean the previous model object in the memory. This can help me to solve memory usage problem since I need many iterations in my problem.

Thanks.

**Comment by odow** [comment]
Julia is a dynamic language. Objects are garbage collected when they fall out of scope (which is why putting the iteration in a function should work). Without an example, it is hard to offer advice.

I suggest that you create a [minimum working example](https://stackoverflow.com/help/mcve) and post it on the [discourse forum](https://discourse.julialang.org/c/domain/opt). Make sure to include a link back to this issue. That way if people run into this problem in the future, they can find it by searching in the Github issues or on the discourse site.

Good luck!

**Comment by odow** [comment]
You could do something like
```julia
function foo()
    model = Model(solver=CplexSolver())
    # ... lots of stuff
    model = nothing
    gc()
end
```
but you're probably better structuring your code to avoid the issue in the first place.

**Comment by Reza-rn** [comment]
@odow 
Thank you very much. This solved my problem.
