### ISSUE TITLE
I would like Julia 1.0.2 to support CPLEX 125

### ISSUE THREAD

**Issue by cdomsa** [JuliaOpt/CPLEX.jl#201]
I have read that Julia 1.0 does not yet support CPLEX125, which is the one I currently use. Can anyone help with this?

**Comment by blegat** [comment]
The support for CPLEX125 was dropped in https://github.com/JuliaOpt/CPLEX.jl/pull/104. Can't you get a more recent version of CPLEX ?

**Comment by odow** [comment]
Hi @cdomsa,

I've just [updated the README](https://github.com/JuliaOpt/CPLEX.jl/pull/202) to clarify that `CPLEX.jl` is an unofficial wrapper that is maintained by volunteers and is not supported by IBM.

Given our limited engineering time, we won't be supporting CPLEX version 12.5. 

If you have to use 12.5 in a commercial setting, contact IBM for support. Otherwise, I suggest you upgrade to the latest v12.8. 

Cheers,
Oscar
