### ISSUE TITLE
internal statuses leak through

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/CPLEX.jl#77]
CPLEX.jl sometimes returns ``:CPXMIP_TIME_LIM_INFEAS`` when it should be ``:UserLimit``

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/CPLEX.jl/pull/78

**Comment by IssamT** [comment]
shouldn't this `:CPXMIP_NODE_LIM_INFEAS`  be also considered as   `:UserLimit`

**Comment by IssamT** [comment]
Looking at the documentation of MathProgBase

> If status does not indicate error or infeasiblity, the other members have the following values:
> 
> objval – optimal objective value
> sol – primal solution vector
> attrs – a dictionary that may contain other relevant attributes such as:
> objbound – Best known lower bound on the objective value

it seems that both

```
:CPXMIP_TIME_LIM_INFEAS
:CPXMIP_NODE_LIM_INFEAS
```

should be translated into `:Unfeasible` and not `:UserLimit`

But then the user does not know if the problem is really unfeasible ...

Maybe we should split the the status `:UserLimit` to somthing like `:UserLimitFeas` and `:UserLimitUnfeas`
